ASPWebsiteShopping/ASPWebsiteShopping/Models/Setting.cs
using System.ComponentModel.DataAnnotations;

namespace ASPWebsiteShopping.Models
{
    public class Setting
    {
        [Key]
        public int Id { get; set; }
        public string ConfigKey { get; set; }
        public string ConfigValue { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public DateTime? DeletedAt { get; set; }
    }
}

ASPWebsiteShopping/ASPWebsiteShopping/Models/SettingViewModel.cs
namespace ASPWebsiteShopping.Models
{
    public class SettingViewModel
    {
        public List<Setting>Settings { get; set; }

        public Setting Setting { get; set; }
    }
}

ASPWebsiteShopping/ASPWebsiteShopping/Controllers/SettingController.cs
using ASPWebsiteShopping.Models;
using ASPWebsiteShopping.Services;
using Microsoft.AspNetCore.Mvc;

namespace ASPWebsiteShopping.Controllers
{
    public class SettingController : Controller
    {
        private readonly IWebHostEnvironment _whostEnvironment;
        private readonly ISettingService _settingService;
        public SettingController(
            IWebHostEnvironment whostEnvironment,
                ISettingService settingService)
        {
            _whostEnvironment = whostEnvironment;
            _settingService = settingService;
        }

        public IActionResult Index()
        {
            var model = new SettingViewModel();
            model.Settings = _settingService.GetList();
            return View("Views/Admin/Setting/Index.cshtml", model);
        }
        public IActionResult Create()
        {
            var model = new SettingViewModel();
            return View("Views/Admin/Setting/Create.cshtml", model);
        }
        [HttpPost]
        public IActionResult Create(SettingViewModel viewModel)
        {
            _settingService.Insert(viewModel);
            return RedirectToAction("Index");
        }
        
        public void Delete(int? id)
        {
            if (id == null || id == 0)
            {
                NotFound();
            }
            var setting = _settingService.GetSettingById(id);
            /*if(setting != null)
            {
                _settingService.DeleteById(setting);
            }*/
            if (setting != null)
            {
                setting.DeletedAt = DateTime.Now;
                /*_settingService.UpdateCate(setting);*/
            }
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var model = new SettingViewModel();
            model.Setting = _settingService.GetSettingById(id);
            if (model.Setting == null)
            {
                return NotFound();
            }
            return View("Views/Admin/Setting/Edit.cshtml", model);
        }
        [HttpPost]
        public IActionResult Edit(SettingViewModel viewModel)
        {
            _settingService.Update(viewModel);
            return RedirectToAction("Index");
        }
    }
}

ASPWebsiteShopping/ASPWebsiteShopping/Views/Admin/Setting/Create.cshtml
@{
    Layout = "/Views/Layouts/_Admin.cshtml";
    ViewData["Title"] = "Thêm mới liên kết";
}
@model SettingViewModel
<div class="content-wrapper">
    
    <form method="post" for-action="Insert" enctype="multipart/form-data">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Setting.ConfigKey"> ConfigKey</label>
                            <input type="text" asp-for="Setting.ConfigKey" class="form-control" placeholder="ConfigKey">
                        </div>
                        <div class="form-group">
                            <label asp-for="Setting.ConfigValue"> ConfigValue</label>
                            <input type="text" asp-for="Setting.ConfigValue" class="form-control" placeholder="ConfigValue">
                        </div>
                       

                        <button type="submit" class="btn btn-primary">Submit</button>
                        
                    </div>
                    <!-- /.col-md-6 -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
    </form>
    <!-- /.content -->
</div>

ASPWebsiteShopping/ASPWebsiteShopping/Views/Admin/Setting/Edit.cshtml
@{
    Layout = "/Views/Layouts/_Admin.cshtml";
    ViewData["Title"] = "Chỉnh sửa liên kết";
}
@model SettingViewModel
<div class="content-wrapper">
    <form method="post" formaction="Edit" enctype="multipart/form-data">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <input type="hidden" asp-for="Setting.Id" />
                        <div class="form-group">
                            <label asp-for="Setting.ConfigKey"> ConfigKey</label>
                            <input type="text" asp-for="Setting.ConfigKey" class="form-control" placeholder="ConfigKey">
                        </div>
                        <div class="form-group">
                            <label asp-for="Setting.ConfigValue"> ConfigValue</label>
                            <input type="text" asp-for="Setting.ConfigValue" class="form-control" placeholder="ConfigValue">
                        </div>
                        

                        <button type="submit" class="btn btn-primary">Submit</button>

                    </div>
                    <!-- /.col-md-6 -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
    </form>
    <!-- /.content -->
</div>

ASPWebsiteShopping/ASPWebsiteShopping/Views/Admin/Setting/Index.cshtml
@{
	Layout = "/Views/Layouts/_ManagerTable.cshtml";
	ViewData["Title"] = "Setting Page";
	ViewData["Page"] = "Liên kết";
}
@model SettingViewModel
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
				<!--Card-->
				<div class="card">
					<div class="card-header">
						<a asp-controller="Setting" asp-action="Create" class="btn btn-primary btn-sm float-right">
							<i class="bi bi-plus-circle"></i>
							Create New Slider
						</a>
					</div>
					@*             <div class="card-header">
					<h3 class="card-title">DataTable with default features</h3>
					</div>*@
					<!-- /.card-header -->
					<div class="card-body">
						<table id="example1" class="table table-bordered table-striped">
							<thead>
								<tr>
									<th>#</th>
									
									<th>
										ConfigKey
									</th>
									<th>
										ConfigValue
									</th>

									<th style="width: 20%">
									</th>
								</tr>
							</thead>
							<tbody>
								@foreach (var obj in @Model.Settings)
								{
									<tr>
										<td>
											#@obj.Id
										</td>
										<td>
											@obj.ConfigKey
										</td>
										
										<td>
											@obj.ConfigValue
										</td>
										<td class="project-actions text-right">
											<div class="w-75 btn-group" role="group">
												<a asp-controller="Setting" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-info btn-sm">
													<i class="fas fa-pencil-alt">
													</i>
													Edit
												</a>
												<a asp-controller="Setting" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger btn-sm action_delete">
													<i class="fas fa-trash">
													</i>
													Delete
												</a>
											</div>
										</td>
									</tr>
								}
							</tbody>
							<tfoot>
								<tr>
									<th>#</th>
									
									<th>
										ConfigKey
									</th>
									<th>
										ConfigValue
									</th>
									<th></th>
								</tr>
							</tfoot>
						</table>
					</div>
					<!-- /.card-body -->
				</div>
				<!-- /.card -->
			</div>
			<!-- /.col -->
		</div>
		<!-- /.row -->
	</div>
	<!-- /.container-fluid -->
</section>