ASPWebsiteShopping/ASPWebsiteShopping/Models/SpeciesViewModel.cs
namespace ASPWebsiteShopping.Models
{
	public class SpeciesViewModel
	{
		public Species Species { get; set; }
		public IEnumerable<Species> SpeciesList { get; set; }

		public ProductAttribute ProductAttribute { get; set; }
	}
}

ASPWebsiteShopping/ASPWebsiteShopping/Controllers/SpeciesController.cs
using ASPWebsiteShopping.Models;
using ASPWebsiteShopping.Services;
using Microsoft.AspNetCore.Mvc;

namespace ASPWebsiteShopping.Controllers
{
	public class SpeciesController : Controller
	{
        private readonly ISpeciesService _SpeciesService;
        private readonly IAttributeService _AttributeService;

        public SpeciesController(ISpeciesService SpeciesService,IAttributeService AttributeService)
        {
            _SpeciesService = SpeciesService;
            _AttributeService = AttributeService;
        }
        public IActionResult Index(int? id)
        {
            var model = new SpeciesViewModel();
            model.SpeciesList = _SpeciesService.GetAllSpeciesListByAttributeId(id);
            var attribute = _AttributeService.GetAttributeById(id);
            model.ProductAttribute = attribute;
            ViewData["Page"] = "Thuộc tính "+attribute.Name.ToString();
            return View("Views/Admin/Species/Index.cshtml", model);
        }
        public IActionResult Create(int? id)
        {
            //
            SpeciesViewModel model = new SpeciesViewModel();
            //get attribute
            var attribute = _AttributeService.GetAttributeById(id);
            model.ProductAttribute = attribute;
            ViewData["AttributeId"] = id;
            ViewData["Page"] = "Thêm chủng loại cho thuộc tính " + attribute.Name.ToString();
            

            return View("Views/Admin/Species/Create.cshtml", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SpeciesViewModel SpeciesViewModel,int attributeId)
        {
            /*            SpeciesViewModel.Speciess = null;
                        SpeciesViewModel.Species.Products = null;
                        SpeciesViewModel.Species.Slug = StringExtendsions.Slugify(SpeciesViewModel.Species.Name);*/
            Species Species = new Species()
            {
                Name = SpeciesViewModel.Species.Name,
                AttributeId= attributeId
            };
            _SpeciesService.AddSpecies(Species);
            return RedirectToAction("Index", new {id= attributeId });
            /*return View("Views/Admin/Species/Create.cshtml", SpeciesViewModel);*/
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var model = new SpeciesViewModel();
            //get Species
            Species Species = _SpeciesService.GetSpeciesById(id);
            if (Species == null)
            {
                return NotFound();
            }
            model.Species = Species;

            return View("Views/Admin/Species/Edit.cshtml", model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SpeciesViewModel SpeciesViewModel)//integer : so nguyen //string:chuoi //obj
        {

            try
            {
                Species Species = _SpeciesService.GetSpeciesById(SpeciesViewModel.Species.Id);

                //Data
                Species.Name = SpeciesViewModel.Species.Name;
                _SpeciesService.UpdateSpecies(Species);
                return RedirectToAction("Index", new { id = Species.AttributeId });
            }
            catch (Exception ex)
            {
                return NotFound();
            }
            /*            return View("Views/Admin/Species/Edit.cshtml", SpeciesViewModel);*/
        }


        [HttpGet]
        public void Delete(int? id)
        {
            if (id == null || id == 0)
            {
                NotFound();
            }
            var Species = _SpeciesService.GetSpeciesById(id);
            if (Species != null)
            {
                _SpeciesService.DeleteByObj(Species);
            }
        }
    }
}

ASPWebsiteShopping/ASPWebsiteShopping/Views/Admin/Species/Create.cshtml
@{
    Layout = "/Views/Layouts/_Admin.cshtml";
    ViewData["Title"] = "Thêm mới chủng loại";
}
@model SpeciesViewModel
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- /.content-header -->
    <!-- Main content -->
     <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h2>@ViewData["Page"]</h2>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <form method="post" formaction="Create">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <input type="hidden" value="@ViewData["AttributeId"]" name="attributeId"/>
                        <div class="form-group">
                            <label asp-for="Species.Name">Tên chủng loại</label>
                            <input type="text" asp-for="Species.Name" class="form-control" placeholder="Enter Species Name">
                            <span asp-validation-for="Species.Name" class="text-danger"></span>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                    <!-- /.col-md-6 -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
    </form>
    <!-- /.content -->
</div>

ASPWebsiteShopping/ASPWebsiteShopping/Views/Admin/Species/Edit.cshtml
@{
    Layout = "/Views/Layouts/_Admin.cshtml";
    ViewData["Title"] = "Chỉnh sửa chủng loại";
}
@model SpeciesViewModel
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h2>Chỉnh sửa chủng loại của thuộc tính @Model.Species.ProductAttribute.Name</h2>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <form method="post" formaction="Edit">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <input type="hidden" asp-for="Species.Id"/>
                        <input type="hidden" asp-for="Species.AttributeId"/>
                        <div class="form-group">
                            <label asp-for="Species.Name">Tên chủng loại</label>
                            <input type="text" asp-for="Species.Name" class="form-control" placeholder="Enter Species Name">
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                    <!-- /.col-md-6 -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
    </form>
    <!-- /.content -->
</div>

ASPWebsiteShopping/ASPWebsiteShopping/Views/Admin/Species/Index.cshtml
@{
	Layout = "/Views/Layouts/_ManagerTable.cshtml";
	ViewData["Title"] = "Species Page";
}
@model SpeciesViewModel
<section class="content">
	  <div class="container-fluid">
		<div class="row">
		  <div class="col-12">
			<!--Card-->
			<div class="card">
				<div class="card-header">
					 <a asp-controller="Species" asp-action="Create" asp-route-id="@Model.ProductAttribute.Id" class="btn btn-primary btn-sm float-right" >
								  <i class="bi bi-plus-circle"></i>
								  Create New Species
							  </a>
				</div>
					@*             <div class="card-header">
                <h3 class="card-title">DataTable with default features</h3>
              </div>*@
			  <!-- /.card-header -->
			  <div class="card-body">
				<table id="example1" class="table table-bordered table-striped">
				  <thead>
				  <tr>
					<th>#</th>
					<th>Species Name</th>
					<th style="width: 20%">
					  </th>
				  </tr>
				  </thead>
				  <tbody>
								@foreach (var obj in @Model.SpeciesList)
								{
							<tr>
								<td>
													#@obj.Id
								</td>
								<td>
											@obj.Name
								</td>
									<td class="project-actions text-right">
									<div class="w-75 btn-group" role="group">
														 <a asp-controller="Species" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-info btn-sm" >
										  <i class="fas fa-pencil-alt">
										  </i>
										  Edit
									  </a>
											  <a asp-controller="Species" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger btn-sm action_delete">
										  <i class="fas fa-trash">
										  </i>
										  Delete
									  </a>
									</div>
								</td>
							</tr>
								}
				  </tbody>
				  <tfoot>
				  <tr>
					<th>#</th>
					<th>Species Name</th>
					<th></th>
				  </tr>
				  </tfoot>
				</table>
			  </div>
			  <!-- /.card-body -->
			</div>
			<!-- /.card -->
		  </div>
		  <!-- /.col -->
		</div>
		<!-- /.row -->
	  </div>
	  <!-- /.container-fluid -->
	</section>