ASPWebsiteShopping/ASPWebsiteShopping/Models/AttributeViewModel.cs
namespace ASPWebsiteShopping.Models
{
    public class AttributeViewModel
    {
        public ProductAttribute ProductAttribute { get; set; }
        public IEnumerable<ProductAttribute> ProductAttributes { get; set; }
    }
}

ASPWebsiteShopping/ASPWebsiteShopping/Controllers/AttributeController.cs
using ASPWebsiteShopping.Components;
using ASPWebsiteShopping.Extendsions;
using ASPWebsiteShopping.Models;
using ASPWebsiteShopping.Services;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;

namespace ASPWebsiteShopping.Controllers
{
    public class AttributeController : Controller
    {
        private readonly IAttributeService _AttributeService;

        public AttributeController(IAttributeService AttributeService)
        {
            _AttributeService = AttributeService;
        }
        [Route("ProductAttribute")]
        [Route("ProductAttribute/Index")]
        public IActionResult Index()
        {
            var model = new AttributeViewModel();
            model.ProductAttributes = _AttributeService.GetAllAttributes();
            return View("Views/Admin/Attribute/Index.cshtml", model);
        }
        public IActionResult Create()
        {
            //
            Console.WriteLine("test");
            var model = new AttributeViewModel();

            return View("Views/Admin/Attribute/Create.cshtml", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(AttributeViewModel AttributeViewModel)
        {
            /*            AttributeViewModel.Attributes = null;
                        AttributeViewModel.Attribute.Products = null;
                        AttributeViewModel.Attribute.Slug = StringExtendsions.Slugify(AttributeViewModel.Attribute.Name);*/
            ProductAttribute Attribute = new ProductAttribute()
            {
                Name = AttributeViewModel.ProductAttribute.Name,
            };
            _AttributeService.AddAttribute(Attribute);
            return RedirectToAction("Index");
            /*return View("Views/Admin/Attribute/Create.cshtml", AttributeViewModel);*/
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var model = new AttributeViewModel();
            IEnumerable<ProductAttribute> Attributes = _AttributeService.GetAllAttributes();
            //get Attribute
            ProductAttribute Attribute = _AttributeService.GetAttributeById(id);
            if (Attribute == null)
            {
                return NotFound();
            }
            model.ProductAttribute = Attribute;

            return View("Views/Admin/Attribute/Edit.cshtml", model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(AttributeViewModel AttributeViewModel)//integer : so nguyen //string:chuoi //obj
        {

            try
            {
                ProductAttribute Attribute = _AttributeService.GetAttributeById(AttributeViewModel.ProductAttribute.Id);

                //Data
                Attribute.Id = AttributeViewModel.ProductAttribute.Id;
                Attribute.Name = AttributeViewModel.ProductAttribute.Name;
                _AttributeService.UpdateAttribute(Attribute);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return NotFound();
            }
            /*            return View("Views/Admin/Attribute/Edit.cshtml", AttributeViewModel);*/
        }


        [HttpGet]
        public void Delete(int? id)
        {
            if (id == null || id == 0)
            {
                NotFound();
            }
            var Attribute = _AttributeService.GetAttributeById(id);
            if (Attribute != null)
            {
                _AttributeService.DeleteByObj(Attribute);
            }
        }
    }
}

ASPWebsiteShopping/ASPWebsiteShopping/Views/Admin/Attribute/Create.cshtml
@{
    Layout = "/Views/Layouts/_Admin.cshtml";
    ViewData["Title"] = "Thêm mới thuộc tính";
}
@model AttributeViewModel
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- /.content-header -->
    <!-- Main content -->
    <form method="post" formaction="Create">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="ProductAttribute.Name">Tên thuộc tính</label>
                            <input type="text" asp-for="ProductAttribute.Name" class="form-control" placeholder="Enter Attribute Name">
                            <span asp-validation-for="ProductAttribute.Name" class="text-danger"></span>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                    <!-- /.col-md-6 -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
    </form>
    <!-- /.content -->
</div>

ASPWebsiteShopping/ASPWebsiteShopping/Views/Admin/Attribute/Edit.cshtml
@{
    Layout = "/Views/Layouts/_Admin.cshtml";
    ViewData["Title"] = "Chỉnh sửa thuộc tính";
}
@model AttributeViewModel
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- /.content-header -->
    <!-- Main content -->
    <form method="post" formaction="Edit">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <input type="hidden" asp-for="ProductAttribute.Id" value="@Model.ProductAttribute.Id"/>
                        <div class="form-group">
                            <label asp-for="ProductAttribute.Name">Tên thuộc tính</label>
                            <input type="text" asp-for="ProductAttribute.Name" class="form-control" placeholder="Enter Attribute Name" value="@Model.ProductAttribute.Name">
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                    <!-- /.col-md-6 -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
    </form>
    <!-- /.content -->
</div>

ASPWebsiteShopping/ASPWebsiteShopping/Views/Admin/Attribute/Index.cshtml
@{
	Layout = "/Views/Layouts/_ManagerTable.cshtml";
	ViewData["Title"] = "Attribute Page";
	ViewData["Page"] = "Thuộc tính sản phẩm";
}
@model AttributeViewModel
<section class="content">
	  <div class="container-fluid">
		<div class="row">
		  <div class="col-12">
			<!--Card-->
			<div class="card">
				<div class="card-header">
					 <a asp-controller="Attribute" asp-action="Create" class="btn btn-primary btn-sm float-right" >
								  <i class="bi bi-plus-circle"></i>
								  Create New Attribute
							  </a>
				</div>
					@*             <div class="card-header">
                <h3 class="card-title">DataTable with default features</h3>
              </div>*@
			  <!-- /.card-header -->
			  <div class="card-body">
				<table id="example1" class="table table-bordered table-striped">
				  <thead>
				  <tr>
					<th>#</th>
					<th>Attribute Name</th>
					<th>Các chủng loại</th>
					<th style="width: 20%">
					  </th>
				  </tr>
				  </thead>
				  <tbody>
								@foreach (var obj in @Model.ProductAttributes)
								{
						<tr>
							<td>
												#@obj.Id
							</td>
							<td>
											@obj.Name
							</td>
							<td>
								@if (obj.ListSpecies.Count > 0)
											{
												var last_item = obj.ListSpecies.Last();
												foreach (var item in obj.ListSpecies)
												{
													if (item.Id.Equals(last_item.Id)) // here I want to check if it is the last item in my ViewBag.List
																				{
														<span>@item.Name</span><br />
													}
													else{
														<span>@item.Name, </span>
													}
												}
											}
									<a asp-controller="Species" asp-action="Index" asp-route-id="@obj.Id" >
										  Cấu hình chủng loại của thuộc tính sản phẩm
									  </a>
							</td>
								<td class="project-actions text-right">
								<div class="w-75 btn-group" role="group">
													 <a asp-controller="Attribute" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-info btn-sm" >
									  <i class="fas fa-pencil-alt">
									  </i>
									  Edit
								  </a>
										  <a asp-controller="Attribute" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger btn-sm action_delete">
									  <i class="fas fa-trash">
									  </i>
									  Delete
								  </a>
								</div>
							</td>
						</tr>
								}
				  </tbody>
				  <tfoot>
				  <tr>
					<th>#</th>
					<th>Attribute Name</th>
					<th>Các chủng loại</th>
					<th></th>
				  </tr>
				  </tfoot>
				</table>
			  </div>
			  <!-- /.card-body -->
			</div>
			<!-- /.card -->
		  </div>
		  <!-- /.col -->
		</div>
		<!-- /.row -->
	  </div>
	  <!-- /.container-fluid -->
	</section>